language: node_js
services:
  - docker

before_install:
  - docker image ls
before_deploy:
  - export IMAGE_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
script:
  - docker-compose build mockserver_14slim

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
