language: node_js
dist: bionic
node_js: 
- lts
services:
  - docker

before_install:
  - docker image ls
before_deploy:
  - export IMAGE_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
install:
  - npm install
script:
  - npm run test
  - docker-compose build mockserver_14slim
  - docker-compose build mockserver_lts

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
