language: node_js
dist: bionic
node_js:
  - stable
services:
  - docker

before_install:
  - docker image ls
before_deploy:
  - export IMAGE_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run coveralls
  - docker-compose build mockserver_14slim
  - docker-compose build mockserver_lts
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
