FROM node:14.2-slim

WORKDIR /usr/app

COPY . .

RUN npm install --production

EXPOSE 80
ENV PORT 80
RUN mkdir /data/response
RUN mkdir /data/configs

ENV NODE_ENV production
ENV STORAGE_PATH /data/responses
ENV CONFIG_PATH /data/configs
RUN npm run build

# Remove the devDependencies after build finished
RUN npm prune

CMD ["npm", "start"]
